[DocTab]
Enable = 0

[InputMethods]
Float = 0
Width = 100

[GUI]
BusyType =

[Tab Applications]
BackgroundType = SolidColor
BackgroundColor = #d8e7f5
TextColor = #000000

[Tab 1Pim]
BackgroundType = SolidColor
BackgroundColor = #d8e7f5
TextColor = #000000

[Tab Settings]
BackgroundType = SolidColor
BackgroundColor = #d8e7f5
TextColor = #000000

[Tab Unsupported]
BackgroundType = SolidColor
BackgroundColor = #d8e7f5
TextColor = #000000
