[DocTab]
Enable = 0

[InputMethods]
Float = 0
Width = 100

[GUI]
BusyType =

[Tab Applications]
BackgroundType = Image
BackgroundImage = launcher/opie-background
TextColor = #000000
Columns = 3

[Tab 1Pim]
BackgroundType = Image
BackgroundImage = launcher/opie-background
TextColor = #000000
Columns = 3

[Tab Settings]
BackgroundType = Image
BackgroundImage = launcher/opie-background
TextColor = #000000
Columns = 3

[Tab Unsupported]
BackgroundType = Image
BackgroundImage = launcher/opie-background
TextColor = #000000
Columns = 3
